# Generated by Django 5.2.14 on 2026-06-02 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelMCER',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('parametros_json', models.JSONField(default=dict)),
                ('orden', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_mcer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.nivelmcer')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submodulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodulos', to='progress.nivelmcer')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido_json', models.JSONField(default=dict)),
                ('nivel_dificultad', models.CharField(max_length=2)),
                ('submodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='progress.submodulo')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoPorEjercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.ejercicio')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='progress.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'ejercicio')},
            },
        ),
    ]
