# Generated by Django 5.2.14 on 2026-06-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='curriculum.ejercicio')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='authentication.perfil')),
            ],
            options={
                'indexes': [models.Index(fields=['perfil', 'ejercicio', 'activo'], name='ix_intento_perfil_ej_activo')],
            },
        ),
    ]
