# Generated by Django 5.2.14 on 2026-06-12 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresoporejercicio',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='authentication.perfil'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
