# Generated by Django 5.2.14 on 2026-06-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_intentoejercicio_transcripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentoejercicio',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
