# Generated by Django 5.2.14 on 2026-06-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_perfil_fecha_ultimo_diagnostico'),
        ('curriculum', '0003_alter_ejercicio_contenido_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('score_speaking', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_listening', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_vocab', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_writing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_resultado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_attempts', to='curriculum.nivelmcer')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_attempts', to='authentication.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
