# Generated by Django 5.2.14 on 2026-06-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcripcion_json', models.JSONField(default=dict)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(default='EN_CURSO', max_length=20)),
                ('iniciada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='authentication.perfil')),
                ('submodulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.submodulo')),
            ],
        ),
    ]
