# Generated by Django 5.2.14 on 2026-06-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionentrevista',
            name='estado',
            field=models.CharField(choices=[('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('ABANDONADA', 'Abandonada')], default='EN_CURSO', max_length=20),
        ),
    ]
