# Generated by Django 5.2.14 on 2026-06-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelMCER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=2, unique=True)),
                ('parametros_json', models.JSONField(default=dict)),
                ('orden', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submodulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodulos', to='curriculum.nivelmcer')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_json', models.JSONField(default=dict)),
                ('nivel_dificultad', models.CharField(max_length=2)),
                ('submodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='curriculum.submodulo')),
            ],
        ),
        migrations.AddIndex(
            model_name='submodulo',
            index=models.Index(fields=['nivel', 'orden'], name='curriculum__nivel_i_71a770_idx'),
        ),
    ]
