# Generated by Django 5.2.14 on 2026-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_ejercicio_texto_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='contenido_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
