# Generated by Django 5.2.14 on 2026-06-12 03:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('PROMOCION', 'Promoción'), ('CERTIFICACION', 'Certificación')], db_index=True, max_length=15)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('detalle_json', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nivel_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.nivelmcer')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='authentication.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.nivelmcer')),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='exams.examenintento')),
            ],
        ),
        migrations.AddIndex(
            model_name='examenintento',
            index=models.Index(fields=['perfil', 'tipo'], name='exams_exame_perfil__3d02ed_idx'),
        ),
    ]
