# Generated by Django 5.2.14 on 2026-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenintento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
