# Generated by Django 5.2.14 on 2026-06-12 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DIAG', 'Test Diagnóstico'), ('A1', 'Nivel A1: Principiante'), ('A2', 'Nivel A2: Elemental'), ('B1', 'Nivel B1: Intermedio')], max_length=4, verbose_name='Nivel al que pertenece')),
                ('question_type', models.CharField(choices=[('CHOICE', 'Gramática/Vocabulario (Opción Múltiple)'), ('LISTENING', 'Comprensión Auditiva (Motor TTS)'), ('SPEAKING', 'Pronunciación (Motor STT)')], max_length=15, verbose_name='Tipo de Pregunta')),
                ('bank_context', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('EXERCISE', 'Exercise'), ('PROMOTION_EXAM', 'Promotion Exam')], db_index=True, default='DIAGNOSTIC', max_length=15, verbose_name='Contexto del banco de preguntas')),
                ('text', models.TextField(verbose_name='Texto de la pregunta (Se permite HTML para negritas o saltos de línea)')),
                ('audio_text', models.CharField(blank=True, help_text='Solo llenar si el tipo es Comprensión Auditiva.', max_length=255, null=True, verbose_name='Texto oculto que leerá el navegador (Para Listening)')),
                ('target_phrase', models.CharField(blank=True, help_text='Solo llenar si el tipo es Pronunciación.', max_length=255, null=True, verbose_name='Frase exacta a evaluar (Para Speaking)')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Banco de Preguntas',
                'ordering': ['level', 'question_type'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Texto de la opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.question', verbose_name='Pregunta asociada')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
    ]
