# Generated by Django 5.2.14 on 2026-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bank_context',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('EXERCISE', 'Exercise'), ('PROMOTION_EXAM', 'Promotion Exam')], db_index=True, default='DIAGNOSTIC', max_length=15, verbose_name='Contexto del banco de preguntas'),
        ),
    ]
