# Generated by Django 5.2.14 on 2026-06-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('CHOICE', 'Gramática/Vocabulario (Opción Múltiple)'), ('LISTENING', 'Comprensión Auditiva (Motor TTS)'), ('SPEAKING', 'Pronunciación (Motor STT)'), ('WRITING', 'Expresión Escrita (Evaluación IA)')], max_length=15, verbose_name='Tipo de Pregunta'),
        ),
    ]
