# Generated by Django 5.2.14 on 2026-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_ultimo_diagnostico',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
